### ISSUE TITLE
Разработать дизайн

### ISSUE THREAD

**Issue by kaa123** [kaa123/UUU#1]
@sashka2281488100500 
@rigby909 
Дизайн страниц регистрации

**Comment by sashka2281488100500** [comment]
Не

**Comment by rigby909** [comment]
Ок

С уважением, Грищенко Элина.

02 Ноя 2016 г. 15:29 пользователь "sashka2281488100500" <
notifications@github.com> написал:

**Comment by sashka2281488100500** [comment]
Кек

**Comment by sashka2281488100500** [comment]
Кек

**Comment by sashka2281488100500** [comment]
Лол

**Comment by sashka2281488100500** [comment]
Гыгы
